### ISSUE TITLE
Validation does not pick up spacing errors within helm templates.

### ISSUE THREAD

**Issue by t0byjohnson** [shipmight/helm-playground#1] opened 2022-03-21 13:26 UTC
Helm will fail if you do not have correct spacing. For example:

` {{- if $.Values.volumes}}`
`command: ["{{ $deployments.command | default $.Values.container.command}}"]`

Where these should be:

` {{- if $.Values.volumes }}`
`command: ["{{ $deployments.command | default $.Values.container.command }}"]`

Helm playground currently succeeds, regardless of the above.

**Comment by codeclown** [comment] 2022-05-07 19:03
I'm not able to reproduce this. Tried:

```bash
helm create test
cd test
helm template . # succeeds
sed -i '' 's/{{- if not .Values.autoscaling.enabled }}/{{- if not .Values.autoscaling.enabled}}/' templates/deployment.yaml
helm template . # still succeeds
```

Please provide Helm version and steps to reproduce. Closing in the meantime.

**Closed by codeclown** 2022-05-07 19:03 UTC
